version: "3"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb?schema=public
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: >
      sh -c "npm run build && npx prisma migrate deploy && node dist/main"

  frontend:
    ports:
      - "3030:3030"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /front
    depends_on:
      - backend

volumes:
  postgres_data:
